"""Nexus AI — Streamlit UI.

IMPORTANT: load_dotenv() must be called before importing agents.orchestrator
so that ANTHROPIC_API_KEY is available when the ADK pipeline is first initialized.
"""

import json
import re
import uuid
from typing import Optional

import streamlit as st
from dotenv import load_dotenv

load_dotenv()  # Must be before agents import

from agents.orchestrator import stream_query  # noqa: E402

# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Nexus AI",
    page_icon="🌌",
    layout="wide",
)

try:
    with open("styles.css") as f:
        st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)
except FileNotFoundError:
    pass


# ── Session state ─────────────────────────────────────────────────────────────
if "messages" not in st.session_state:
    st.session_state.messages: list[dict] = []

if "session_id" not in st.session_state:
    st.session_state.session_id = str(uuid.uuid4())

if "history" not in st.session_state:
    st.session_state.history: list[dict] = []


# ── Rendering helpers ─────────────────────────────────────────────────────────

def _parse_response(text: str) -> Optional[dict]:
    """Extract and parse JSON from the agent's response text."""
    try:
        return json.loads(text.strip())
    except json.JSONDecodeError:
        pass
    match = re.search(r"\{[\s\S]*\}", text)
    if match:
        try:
            return json.loads(match.group(0))
        except json.JSONDecodeError:
            pass
    return None


def _to_markdown_export(data: dict) -> str:
    """Convert structured recommendation JSON to a shareable Markdown report."""
    medals = {1: "🥇", 2: "🥈", 3: "🥉"}
    lines = ["# Nexus AI — Model Recommendation Report\n"]
    lines.append(f"**Winner: {data.get('winner', 'N/A')}**")
    lines.append(f"> {data.get('winner_reason', '')}\n")

    top_3 = data.get("top_3") or []
    if top_3:
        lines.append("## Comparison Table\n")
        lines.append("| Rank | Model | Type | Benchmark | Output $/M | Speed | Context | License |")
        lines.append("|------|-------|------|-----------|------------|-------|---------|---------|")
        for m in top_3:
            lines.append(
                f"| {medals.get(m.get('rank', 0), '')} | {m.get('name', '')} | {m.get('type', '')} "
                f"| {m.get('benchmark', '')} | {m.get('output_cost_per_m', '')} "
                f"| {m.get('speed_tps', '')} | {m.get('context_k', '')} | {m.get('license', '')} |"
            )
        lines.append("")

        for m in top_3:
            rank = m.get("rank", 0)
            lines.append(f"\n## {medals.get(rank, '')} {m.get('name', '')}")
            lines.append(
                f"**Model ID:** `{m.get('model_id', '')}` · "
                f"**Provider:** {m.get('provider', '')} · **Type:** {m.get('type', '')}"
            )
            if m.get("url"):
                lines.append(f"**Link:** {m['url']}")
            lines.append(f"**GPU Requirement:** {m.get('gpu_requirement', 'N/A')}\n")
            lines.append("**Strengths:**")
            for s in (m.get("strengths") or []):
                lines.append(f"- {s}")
            lines.append("\n**Weaknesses:**")
            for w in (m.get("weaknesses") or []):
                lines.append(f"- {w}")
            lines.append(f"\n**Best for:** {m.get('best_for', '')}")

    if data.get("critique"):
        lines.append("\n## Expert Analysis\n")
        if data.get("comparison_notes"):
            lines.append(f"*{data['comparison_notes']}*\n")
        lines.append(data["critique"])

    similar = data.get("similar_models") or []
    if similar:
        lines.append("\n## Similar Models Worth Watching\n")
        for m in similar:
            lines.append(f"- **{m.get('name', '')}**: {m.get('why', '')}")

    refs = data.get("reading_references") or []
    if refs:
        lines.append("\n## References\n")
        for r in refs:
            lines.append(f"- [{r.get('title', 'Link')}]({r.get('url', '#')})")

    lines.append("\n---\n*Generated by Nexus AI — verify benchmarks and pricing independently.*")
    return "\n".join(lines)


def _render_model_card(model: dict, col):
    """Render a single model card inside a Streamlit column."""
    medals = {1: "🥇", 2: "🥈", 3: "🥉"}
    rank = model.get("rank", 0)

    with col:
        st.markdown(f"### {medals.get(rank, '')} {model.get('name', 'Unknown')}")
        st.caption(f"`{model.get('model_id', '')}` · {model.get('provider', '')} · {model.get('type', '')}")
        if model.get("url"):
            st.markdown(f"[View model →]({model['url']})")

        st.divider()

        m1, m2 = st.columns(2)
        with m1:
            st.metric("Output cost", model.get("output_cost_per_m", "N/A"))
            st.metric("Speed", model.get("speed_tps", "N/A"))
        with m2:
            st.metric("Context", model.get("context_k", "N/A"))
            st.metric("GPU req.", model.get("gpu_requirement", "N/A"))

        st.markdown(
            f"**Benchmark:** {model.get('benchmark', 'N/A')}  \n"
            f"**License:** `{model.get('license', 'N/A')}`"
        )
        st.divider()

        strengths = model.get("strengths") or []
        if strengths:
            st.markdown("**✅ Strengths**")
            for s in strengths:
                st.markdown(f"- {s}")

        weaknesses = model.get("weaknesses") or []
        if weaknesses:
            st.markdown("**⚠️ Weaknesses**")
            for w in weaknesses:
                st.markdown(f"- {w}")

        if model.get("best_for"):
            st.info(f"**Best for:** {model['best_for']}")


def render_recommendations(response_text: str):
    """Parse JSON response and render with Streamlit components; falls back to markdown."""
    data = _parse_response(response_text)

    if not data or "top_3" not in data:
        st.markdown(response_text)
        return

    top_3 = data.get("top_3") or []
    medals = {1: "🥇", 2: "🥈", 3: "🥉"}

    # Winner banner + export button side by side
    col_win, col_export = st.columns([4, 1])
    with col_win:
        if data.get("winner"):
            st.success(f"🏆 **Recommended: {data['winner']}** — {data.get('winner_reason', '')}")
    with col_export:
        st.download_button(
            label="⬇ Export",
            data=_to_markdown_export(data),
            file_name="nexus_ai_recommendation.md",
            mime="text/markdown",
            use_container_width=True,
        )

    # Model cards
    if top_3:
        cols = st.columns(len(top_3), gap="medium")
        for model, col in zip(top_3, cols):
            _render_model_card(model, col)

    # Comparison table
    if top_3:
        st.subheader("Side-by-Side Comparison")
        table = {
            "": [f"{medals.get(m.get('rank', 0), '')} {m.get('name', '')}" for m in top_3],
            "Type": [m.get("type", "N/A") for m in top_3],
            "Benchmark": [m.get("benchmark", "N/A") for m in top_3],
            "Input $/M": [m.get("input_cost_per_m", "N/A") for m in top_3],
            "Output $/M": [m.get("output_cost_per_m", "N/A") for m in top_3],
            "Speed": [m.get("speed_tps", "N/A") for m in top_3],
            "Context": [m.get("context_k", "N/A") for m in top_3],
            "GPU": [m.get("gpu_requirement", "N/A") for m in top_3],
            "License": [m.get("license", "N/A") for m in top_3],
        }
        st.dataframe(table, use_container_width=True, hide_index=True)

    # Expert analysis
    if data.get("critique") or data.get("comparison_notes"):
        st.subheader("Expert Analysis")
        if data.get("comparison_notes"):
            st.markdown(f"*{data['comparison_notes']}*")
        if data.get("critique"):
            st.markdown(data["critique"])

    # Similar models
    similar = data.get("similar_models") or []
    if similar:
        with st.expander("Similar Models Worth Watching"):
            for m in similar:
                st.markdown(f"**{m.get('name', '')}** — {m.get('why', '')}")

    # References
    refs = data.get("reading_references") or []
    if refs:
        st.subheader("📚 References")
        for ref in refs:
            st.markdown(f"- [{ref.get('title', 'Link')}]({ref.get('url', '#')})")

    st.divider()
    st.caption(
        "⚠️ *Nexus AI is an experimental agent. Information is sourced via live web scraping "
        "and may contain inaccuracies. Verify critical benchmarks and pricing independently.*"
    )


# ── Sidebar ───────────────────────────────────────────────────────────────────
with st.sidebar:
    st.title("Nexus AI")
    st.caption("Powered by Google ADK + Claude")
    st.divider()

    if st.button("＋ New Query", use_container_width=True, type="primary"):
        if st.session_state.messages:
            first_user = next(
                (m["content"] for m in st.session_state.messages if m["role"] == "user"),
                "Session",
            )
            st.session_state.history.append({
                "id": st.session_state.session_id,
                "title": first_user[:55] + ("…" if len(first_user) > 55 else ""),
                "messages": list(st.session_state.messages),
            })
        st.session_state.messages = []
        st.session_state.session_id = str(uuid.uuid4())
        st.rerun()

    if st.session_state.history:
        st.divider()
        st.subheader("Past Queries")
        for entry in reversed(st.session_state.history):
            if st.button(entry["title"], key=f"hist_{entry['id']}", use_container_width=True):
                st.session_state.messages = list(entry["messages"])
                st.session_state.session_id = entry["id"]
                st.rerun()

    st.divider()
    st.caption("Sources: HuggingFace Hub · Chatbot Arena · Web Search")


# ── Main structure ─────────────────────────────────────────────────────────────
st.title("Nexus AI: Model Intelligence Engine")
st.caption(
    "A real-time analytics engine that autonomously scours the latest benchmarks, pricing data, "
    "and leaderboards to pinpoint the absolute best AI model for your exact constraints."
)

tab_search, tab_about = st.tabs(["🚀 Model Search", "🧠 Architecture & Creator"])

with tab_about:
    st.header("👨‍💻 Ahsan Ijaz")
    st.markdown("### Chief AI Architect @ Standard Chartered")
    st.markdown(
        "I am the **Chief AI Architect at Standard Chartered**, where I spearhead the platform architecture, "
        "technical strategy, and enterprise-wide scaling of AI adoption across the group. "
        "I am deeply passionate about designing autonomous, agentic systems that bridge the gap between "
        "cutting-edge foundation models and real-world product needs."
    )
    st.markdown("🔗 **[LinkedIn](https://www.linkedin.com/in/ahsan-ijaz/)** | 🐙 **[GitHub](https://github.com/ahsanijaz/)**")
    st.divider()
    st.subheader("⚙️ System Architecture")
    st.markdown(
        "**Nexus AI** is built on a multi-agent orchestrated research pipeline designed to guarantee fresh knowledge:\n"
        "- **Google ADK**: Powers stateful orchestration of autonomous agents.\n"
        "- **LiteLLM**: Routes requests to Claude Sonnet via the Anthropic API.\n"
        "- **Web Search & Data Agents**: Pulls latest pricing, benchmarks, and docs via live web scraping.\n"
    )

# ── Search tab: all chat UI lives here so messages render inside the tab ──────
with tab_search:
    if not st.session_state.messages:
        with st.chat_message("assistant", avatar="🌌"):
            st.markdown(
                "**What are you building?** Describe your use case and constraints:\n\n"
                "- *I need a cheap multilingual OCR model with high throughput, minimal GPU*\n"
                "- *Best open-source code generation model under Apache 2.0 license*\n"
                "- *Low-latency API model for real-time chat, under \\$5/M tokens*\n"
                "- *Small reasoning model that runs on a single A100*\n\n"
                "You can follow up too — e.g. *make it cheaper* or *I need longer context*."
            )

    # Render conversation history
    for msg in st.session_state.messages:
        avatar = "👤" if msg["role"] == "user" else "🌌"
        with st.chat_message(msg["role"], avatar=avatar):
            if msg["role"] == "assistant":
                render_recommendations(msg["content"])
            else:
                st.markdown(msg["content"])

    # Chat input — inside tab so new messages render here, not below the tabs
    if prompt := st.chat_input("Describe your AI task and requirements…"):
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user", avatar="👤"):
            st.markdown(prompt)

        with st.chat_message("assistant", avatar="🌌"):
            response = ""
            try:
                with st.status("Researching current models…", expanded=True) as status:
                    for update in stream_query(
                        query=prompt,
                        session_id=st.session_state.session_id,
                    ):
                        if update["type"] == "agent":
                            text = update["text"]
                            # Suppress data blobs (>200 chars) that leaked as agent events
                            st.write(f"**{text}**" if len(text) <= 200 else "**Processing gathered data…**")
                        elif update["type"] == "tool":
                            st.write(f"&nbsp;&nbsp;&nbsp;↳ {update['text']}")
                        elif update["type"] == "result":
                            response = update["text"]
                            status.update(label="Done!", state="complete", expanded=False)
                        elif update["type"] == "error":
                            status.update(label="Error", state="error", expanded=True)
                            st.error(update["text"])
                            st.session_state.messages.pop()
                            st.stop()
            except RuntimeError as exc:
                st.error(str(exc))
                st.session_state.messages.pop()
                st.stop()

            if response:
                render_recommendations(response)

        st.session_state.messages.append({"role": "assistant", "content": response})
